//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealershipBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasketAutopart
    {
        public int User_id { get; set; }
        public int Item_id { get; set; }
        public int BasketAutopart_id { get; set; }
        public Nullable<bool> Sold { get; set; }
        public int AmountItem { get; set; }
    
        public virtual User User { get; set; }
        public virtual WarehouseAutopart WarehouseAutopart { get; set; }
    }
}
