//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealershipBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryService_Warehouse
    {
        public int Category_service_id { get; set; }
        public int Item_id { get; set; }
        public int CW_id { get; set; }
    
        public virtual CategoryService CategoryService { get; set; }
        public virtual WarehouseAutopart WarehouseAutopart { get; set; }
    }
}
