//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealershipBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationService
    {
        public int User_id { get; set; }
        public System.DateTime Date { get; set; }
        public int Reg_id { get; set; }
        public int Lot { get; set; }
        public bool Actual { get; set; }
        public int Category_service_id { get; set; }
    
        public virtual CategoryService CategoryService { get; set; }
        public virtual User User { get; set; }
    }
}
