//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealershipBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseAutopart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WarehouseAutopart()
        {
            this.BasketAutopart = new HashSet<BasketAutopart>();
            this.CategoryService_Warehouse = new HashSet<CategoryService_Warehouse>();
        }
    
        public int Item_id { get; set; }
        public string Type_item { get; set; }
        public string Name_item { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> ForSale { get; set; }
        public int Price { get; set; }
        public Nullable<int> Service_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketAutopart> BasketAutopart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryService_Warehouse> CategoryService_Warehouse { get; set; }
        public virtual Service Service { get; set; }
    }
}
