//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealershipBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneService
    {
        public string Name { get; set; }
        public string Number { get; set; }
        public int Phone_service_id { get; set; }
        public Nullable<int> User_id_Service { get; set; }
    
        public virtual User User { get; set; }
    }
}
